/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Density } from "./utils/config-scope";
export { Density } from "./utils/config-scope";
export namespace Components {
    /**
     * @component lux-button
     * @experimental A button component that automatically adapts to density and color settings
     * from the nearest lux-scope ancestor.
     * @example ```html
     * <lux-button>Click me</lux-button>
     * <lux-button variant="primary">Primary</lux-button>
     * <lux-button variant="secondary" disabled>Disabled</lux-button>
     * ```
     */
    interface LuxButton {
        /**
          * Disabled state
          * @experimental 
          * @default false
         */
        "disabled": boolean;
        /**
          * Button type
          * @experimental 
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button variant
          * @experimental 
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'outline' | 'ghost';
    }
    /**
     * @component lux-card
     * @experimental A card component for displaying content in a contained area.
     * @example ```html
     * <lux-card>
     *   <lux-heading level="3">Card Title</lux-heading>
     *   <lux-text>Card content goes here</lux-text>
     * </lux-card>
     * ```
     */
    interface LuxCard {
        /**
          * Card variant
          * @experimental
         */
        "variant"?: 'default' | 'outlined' | 'elevated';
    }
    /**
     * @component lux-heading
     * @experimental A heading component with semantic HTML and automatic styling.
     * @example ```html
     * <lux-heading level="1">Main Heading</lux-heading>
     * <lux-heading level="2">Subheading</lux-heading>
     * ```
     */
    interface LuxHeading {
        /**
          * Heading level (1-6)
          * @experimental 
          * @default 1
         */
        "level": 1 | 2 | 3 | 4 | 5 | 6;
    }
    /**
     * @component lux-icon
     * @experimental An icon component that uses Font Awesome icons with tree-shaking support.
     * @example ```html
     * <lux-icon name="check"></lux-icon>
     * <lux-icon name="user" size="lg"></lux-icon>
     * ```
     */
    interface LuxIcon {
        /**
          * Icon name (Font Awesome icon name without 'fa-' prefix)
          * @experimental
         */
        "name": string;
        /**
          * Icon size
          * @experimental
         */
        "size"?: 'xs' | 'sm' | 'base' | 'lg' | 'xl' | '2xl';
    }
    /**
     * @component lux-scope
     * @experimental A configuration scoping component that applies density and color settings
     * to all descendant Lux components via CSS custom properties.
     * This component does not render any visual element, but provides configuration
     * context through the DOM hierarchy.
     * @example ```html
     * <lux-scope density="compact" main-color="#ff0000">
     *   <lux-button>Button</lux-button>
     *   <lux-card>Card content</lux-card>
     * </lux-scope>
     * ```
     */
    interface LuxScope {
        /**
          * Density setting for child components
          * @experimental
         */
        "density"?: Density;
        /**
          * Main color for child components
          * @experimental
         */
        "mainColor"?: string;
    }
    /**
     * @component lux-tab
     * @experimental A single tab panel for use within lux-tabs.
     * @example ```html
     * <lux-tab label="Settings">Tab content</lux-tab>
     * ```
     */
    interface LuxTab {
        /**
          * Tab label
          * @experimental
         */
        "label": string;
    }
    /**
     * @component lux-table
     * @experimental A data table component built on ag-Grid with custom Lux styling.
     * Requires ag-grid-community (and optionally ag-grid-angular or ag-grid-react)
     * as a peer dependency.
     * This component wraps ag-Grid and applies Lux design tokens for consistent
     * styling across the component library.
     * @example ```html
     * <lux-table
     *   column-defs='[{"field": "name"}, {"field": "age"}]'
     *   row-data='[{"name": "John", "age": 30}]'
     * ></lux-table>
     * ```
     */
    interface LuxTable {
        /**
          * Column definitions as JSON string
          * @experimental
         */
        "columnDefs"?: string;
        /**
          * Grid options as JSON string
          * @experimental
         */
        "gridOptions"?: string;
        /**
          * Row data as JSON string
          * @experimental
         */
        "rowData"?: string;
    }
    /**
     * @component lux-tabs
     * @experimental A tabs component for organizing content into multiple panels.
     * @example ```html
     * <lux-tabs>
     *   <lux-tab label="Tab 1">Content 1</lux-tab>
     *   <lux-tab label="Tab 2">Content 2</lux-tab>
     * </lux-tabs>
     * ```
     */
    interface LuxTabs {
        /**
          * Active tab index
          * @experimental 
          * @default 0
         */
        "activeIndex": number;
    }
    /**
     * @component lux-text
     * @experimental A text component that displays text content with automatic density adaptation.
     * @example ```html
     * <lux-text>Regular text</lux-text>
     * <lux-text size="lg" weight="bold">Large bold text</lux-text>
     * ```
     */
    interface LuxText {
        /**
          * Text color variant
          * @experimental
         */
        "color"?: 'default' | 'muted' | 'primary' | 'error' | 'success';
        /**
          * Text size
          * @experimental
         */
        "size"?: 'xs' | 'sm' | 'base' | 'lg' | 'xl';
        /**
          * Font weight
          * @experimental
         */
        "weight"?: 'normal' | 'medium' | 'semibold' | 'bold';
    }
}
export interface LuxButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLuxButtonElement;
}
declare global {
    interface HTMLLuxButtonElementEventMap {
        "luxClick": MouseEvent;
    }
    /**
     * @component lux-button
     * @experimental A button component that automatically adapts to density and color settings
     * from the nearest lux-scope ancestor.
     * @example ```html
     * <lux-button>Click me</lux-button>
     * <lux-button variant="primary">Primary</lux-button>
     * <lux-button variant="secondary" disabled>Disabled</lux-button>
     * ```
     */
    interface HTMLLuxButtonElement extends Components.LuxButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLuxButtonElementEventMap>(type: K, listener: (this: HTMLLuxButtonElement, ev: LuxButtonCustomEvent<HTMLLuxButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLuxButtonElementEventMap>(type: K, listener: (this: HTMLLuxButtonElement, ev: LuxButtonCustomEvent<HTMLLuxButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLuxButtonElement: {
        prototype: HTMLLuxButtonElement;
        new (): HTMLLuxButtonElement;
    };
    /**
     * @component lux-card
     * @experimental A card component for displaying content in a contained area.
     * @example ```html
     * <lux-card>
     *   <lux-heading level="3">Card Title</lux-heading>
     *   <lux-text>Card content goes here</lux-text>
     * </lux-card>
     * ```
     */
    interface HTMLLuxCardElement extends Components.LuxCard, HTMLStencilElement {
    }
    var HTMLLuxCardElement: {
        prototype: HTMLLuxCardElement;
        new (): HTMLLuxCardElement;
    };
    /**
     * @component lux-heading
     * @experimental A heading component with semantic HTML and automatic styling.
     * @example ```html
     * <lux-heading level="1">Main Heading</lux-heading>
     * <lux-heading level="2">Subheading</lux-heading>
     * ```
     */
    interface HTMLLuxHeadingElement extends Components.LuxHeading, HTMLStencilElement {
    }
    var HTMLLuxHeadingElement: {
        prototype: HTMLLuxHeadingElement;
        new (): HTMLLuxHeadingElement;
    };
    /**
     * @component lux-icon
     * @experimental An icon component that uses Font Awesome icons with tree-shaking support.
     * @example ```html
     * <lux-icon name="check"></lux-icon>
     * <lux-icon name="user" size="lg"></lux-icon>
     * ```
     */
    interface HTMLLuxIconElement extends Components.LuxIcon, HTMLStencilElement {
    }
    var HTMLLuxIconElement: {
        prototype: HTMLLuxIconElement;
        new (): HTMLLuxIconElement;
    };
    /**
     * @component lux-scope
     * @experimental A configuration scoping component that applies density and color settings
     * to all descendant Lux components via CSS custom properties.
     * This component does not render any visual element, but provides configuration
     * context through the DOM hierarchy.
     * @example ```html
     * <lux-scope density="compact" main-color="#ff0000">
     *   <lux-button>Button</lux-button>
     *   <lux-card>Card content</lux-card>
     * </lux-scope>
     * ```
     */
    interface HTMLLuxScopeElement extends Components.LuxScope, HTMLStencilElement {
    }
    var HTMLLuxScopeElement: {
        prototype: HTMLLuxScopeElement;
        new (): HTMLLuxScopeElement;
    };
    /**
     * @component lux-tab
     * @experimental A single tab panel for use within lux-tabs.
     * @example ```html
     * <lux-tab label="Settings">Tab content</lux-tab>
     * ```
     */
    interface HTMLLuxTabElement extends Components.LuxTab, HTMLStencilElement {
    }
    var HTMLLuxTabElement: {
        prototype: HTMLLuxTabElement;
        new (): HTMLLuxTabElement;
    };
    /**
     * @component lux-table
     * @experimental A data table component built on ag-Grid with custom Lux styling.
     * Requires ag-grid-community (and optionally ag-grid-angular or ag-grid-react)
     * as a peer dependency.
     * This component wraps ag-Grid and applies Lux design tokens for consistent
     * styling across the component library.
     * @example ```html
     * <lux-table
     *   column-defs='[{"field": "name"}, {"field": "age"}]'
     *   row-data='[{"name": "John", "age": 30}]'
     * ></lux-table>
     * ```
     */
    interface HTMLLuxTableElement extends Components.LuxTable, HTMLStencilElement {
    }
    var HTMLLuxTableElement: {
        prototype: HTMLLuxTableElement;
        new (): HTMLLuxTableElement;
    };
    /**
     * @component lux-tabs
     * @experimental A tabs component for organizing content into multiple panels.
     * @example ```html
     * <lux-tabs>
     *   <lux-tab label="Tab 1">Content 1</lux-tab>
     *   <lux-tab label="Tab 2">Content 2</lux-tab>
     * </lux-tabs>
     * ```
     */
    interface HTMLLuxTabsElement extends Components.LuxTabs, HTMLStencilElement {
    }
    var HTMLLuxTabsElement: {
        prototype: HTMLLuxTabsElement;
        new (): HTMLLuxTabsElement;
    };
    /**
     * @component lux-text
     * @experimental A text component that displays text content with automatic density adaptation.
     * @example ```html
     * <lux-text>Regular text</lux-text>
     * <lux-text size="lg" weight="bold">Large bold text</lux-text>
     * ```
     */
    interface HTMLLuxTextElement extends Components.LuxText, HTMLStencilElement {
    }
    var HTMLLuxTextElement: {
        prototype: HTMLLuxTextElement;
        new (): HTMLLuxTextElement;
    };
    interface HTMLElementTagNameMap {
        "lux-button": HTMLLuxButtonElement;
        "lux-card": HTMLLuxCardElement;
        "lux-heading": HTMLLuxHeadingElement;
        "lux-icon": HTMLLuxIconElement;
        "lux-scope": HTMLLuxScopeElement;
        "lux-tab": HTMLLuxTabElement;
        "lux-table": HTMLLuxTableElement;
        "lux-tabs": HTMLLuxTabsElement;
        "lux-text": HTMLLuxTextElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component lux-button
     * @experimental A button component that automatically adapts to density and color settings
     * from the nearest lux-scope ancestor.
     * @example ```html
     * <lux-button>Click me</lux-button>
     * <lux-button variant="primary">Primary</lux-button>
     * <lux-button variant="secondary" disabled>Disabled</lux-button>
     * ```
     */
    interface LuxButton {
        /**
          * Disabled state
          * @experimental 
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Click event
          * @experimental
         */
        "onLuxClick"?: (event: LuxButtonCustomEvent<MouseEvent>) => void;
        /**
          * Button type
          * @experimental 
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button variant
          * @experimental 
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'outline' | 'ghost';
    }
    /**
     * @component lux-card
     * @experimental A card component for displaying content in a contained area.
     * @example ```html
     * <lux-card>
     *   <lux-heading level="3">Card Title</lux-heading>
     *   <lux-text>Card content goes here</lux-text>
     * </lux-card>
     * ```
     */
    interface LuxCard {
        /**
          * Card variant
          * @experimental
         */
        "variant"?: 'default' | 'outlined' | 'elevated';
    }
    /**
     * @component lux-heading
     * @experimental A heading component with semantic HTML and automatic styling.
     * @example ```html
     * <lux-heading level="1">Main Heading</lux-heading>
     * <lux-heading level="2">Subheading</lux-heading>
     * ```
     */
    interface LuxHeading {
        /**
          * Heading level (1-6)
          * @experimental 
          * @default 1
         */
        "level"?: 1 | 2 | 3 | 4 | 5 | 6;
    }
    /**
     * @component lux-icon
     * @experimental An icon component that uses Font Awesome icons with tree-shaking support.
     * @example ```html
     * <lux-icon name="check"></lux-icon>
     * <lux-icon name="user" size="lg"></lux-icon>
     * ```
     */
    interface LuxIcon {
        /**
          * Icon name (Font Awesome icon name without 'fa-' prefix)
          * @experimental
         */
        "name": string;
        /**
          * Icon size
          * @experimental
         */
        "size"?: 'xs' | 'sm' | 'base' | 'lg' | 'xl' | '2xl';
    }
    /**
     * @component lux-scope
     * @experimental A configuration scoping component that applies density and color settings
     * to all descendant Lux components via CSS custom properties.
     * This component does not render any visual element, but provides configuration
     * context through the DOM hierarchy.
     * @example ```html
     * <lux-scope density="compact" main-color="#ff0000">
     *   <lux-button>Button</lux-button>
     *   <lux-card>Card content</lux-card>
     * </lux-scope>
     * ```
     */
    interface LuxScope {
        /**
          * Density setting for child components
          * @experimental
         */
        "density"?: Density;
        /**
          * Main color for child components
          * @experimental
         */
        "mainColor"?: string;
    }
    /**
     * @component lux-tab
     * @experimental A single tab panel for use within lux-tabs.
     * @example ```html
     * <lux-tab label="Settings">Tab content</lux-tab>
     * ```
     */
    interface LuxTab {
        /**
          * Tab label
          * @experimental
         */
        "label": string;
    }
    /**
     * @component lux-table
     * @experimental A data table component built on ag-Grid with custom Lux styling.
     * Requires ag-grid-community (and optionally ag-grid-angular or ag-grid-react)
     * as a peer dependency.
     * This component wraps ag-Grid and applies Lux design tokens for consistent
     * styling across the component library.
     * @example ```html
     * <lux-table
     *   column-defs='[{"field": "name"}, {"field": "age"}]'
     *   row-data='[{"name": "John", "age": 30}]'
     * ></lux-table>
     * ```
     */
    interface LuxTable {
        /**
          * Column definitions as JSON string
          * @experimental
         */
        "columnDefs"?: string;
        /**
          * Grid options as JSON string
          * @experimental
         */
        "gridOptions"?: string;
        /**
          * Row data as JSON string
          * @experimental
         */
        "rowData"?: string;
    }
    /**
     * @component lux-tabs
     * @experimental A tabs component for organizing content into multiple panels.
     * @example ```html
     * <lux-tabs>
     *   <lux-tab label="Tab 1">Content 1</lux-tab>
     *   <lux-tab label="Tab 2">Content 2</lux-tab>
     * </lux-tabs>
     * ```
     */
    interface LuxTabs {
        /**
          * Active tab index
          * @experimental 
          * @default 0
         */
        "activeIndex"?: number;
    }
    /**
     * @component lux-text
     * @experimental A text component that displays text content with automatic density adaptation.
     * @example ```html
     * <lux-text>Regular text</lux-text>
     * <lux-text size="lg" weight="bold">Large bold text</lux-text>
     * ```
     */
    interface LuxText {
        /**
          * Text color variant
          * @experimental
         */
        "color"?: 'default' | 'muted' | 'primary' | 'error' | 'success';
        /**
          * Text size
          * @experimental
         */
        "size"?: 'xs' | 'sm' | 'base' | 'lg' | 'xl';
        /**
          * Font weight
          * @experimental
         */
        "weight"?: 'normal' | 'medium' | 'semibold' | 'bold';
    }
    interface IntrinsicElements {
        "lux-button": LuxButton;
        "lux-card": LuxCard;
        "lux-heading": LuxHeading;
        "lux-icon": LuxIcon;
        "lux-scope": LuxScope;
        "lux-tab": LuxTab;
        "lux-table": LuxTable;
        "lux-tabs": LuxTabs;
        "lux-text": LuxText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component lux-button
             * @experimental A button component that automatically adapts to density and color settings
             * from the nearest lux-scope ancestor.
             * @example ```html
             * <lux-button>Click me</lux-button>
             * <lux-button variant="primary">Primary</lux-button>
             * <lux-button variant="secondary" disabled>Disabled</lux-button>
             * ```
             */
            "lux-button": LocalJSX.LuxButton & JSXBase.HTMLAttributes<HTMLLuxButtonElement>;
            /**
             * @component lux-card
             * @experimental A card component for displaying content in a contained area.
             * @example ```html
             * <lux-card>
             *   <lux-heading level="3">Card Title</lux-heading>
             *   <lux-text>Card content goes here</lux-text>
             * </lux-card>
             * ```
             */
            "lux-card": LocalJSX.LuxCard & JSXBase.HTMLAttributes<HTMLLuxCardElement>;
            /**
             * @component lux-heading
             * @experimental A heading component with semantic HTML and automatic styling.
             * @example ```html
             * <lux-heading level="1">Main Heading</lux-heading>
             * <lux-heading level="2">Subheading</lux-heading>
             * ```
             */
            "lux-heading": LocalJSX.LuxHeading & JSXBase.HTMLAttributes<HTMLLuxHeadingElement>;
            /**
             * @component lux-icon
             * @experimental An icon component that uses Font Awesome icons with tree-shaking support.
             * @example ```html
             * <lux-icon name="check"></lux-icon>
             * <lux-icon name="user" size="lg"></lux-icon>
             * ```
             */
            "lux-icon": LocalJSX.LuxIcon & JSXBase.HTMLAttributes<HTMLLuxIconElement>;
            /**
             * @component lux-scope
             * @experimental A configuration scoping component that applies density and color settings
             * to all descendant Lux components via CSS custom properties.
             * This component does not render any visual element, but provides configuration
             * context through the DOM hierarchy.
             * @example ```html
             * <lux-scope density="compact" main-color="#ff0000">
             *   <lux-button>Button</lux-button>
             *   <lux-card>Card content</lux-card>
             * </lux-scope>
             * ```
             */
            "lux-scope": LocalJSX.LuxScope & JSXBase.HTMLAttributes<HTMLLuxScopeElement>;
            /**
             * @component lux-tab
             * @experimental A single tab panel for use within lux-tabs.
             * @example ```html
             * <lux-tab label="Settings">Tab content</lux-tab>
             * ```
             */
            "lux-tab": LocalJSX.LuxTab & JSXBase.HTMLAttributes<HTMLLuxTabElement>;
            /**
             * @component lux-table
             * @experimental A data table component built on ag-Grid with custom Lux styling.
             * Requires ag-grid-community (and optionally ag-grid-angular or ag-grid-react)
             * as a peer dependency.
             * This component wraps ag-Grid and applies Lux design tokens for consistent
             * styling across the component library.
             * @example ```html
             * <lux-table
             *   column-defs='[{"field": "name"}, {"field": "age"}]'
             *   row-data='[{"name": "John", "age": 30}]'
             * ></lux-table>
             * ```
             */
            "lux-table": LocalJSX.LuxTable & JSXBase.HTMLAttributes<HTMLLuxTableElement>;
            /**
             * @component lux-tabs
             * @experimental A tabs component for organizing content into multiple panels.
             * @example ```html
             * <lux-tabs>
             *   <lux-tab label="Tab 1">Content 1</lux-tab>
             *   <lux-tab label="Tab 2">Content 2</lux-tab>
             * </lux-tabs>
             * ```
             */
            "lux-tabs": LocalJSX.LuxTabs & JSXBase.HTMLAttributes<HTMLLuxTabsElement>;
            /**
             * @component lux-text
             * @experimental A text component that displays text content with automatic density adaptation.
             * @example ```html
             * <lux-text>Regular text</lux-text>
             * <lux-text size="lg" weight="bold">Large bold text</lux-text>
             * ```
             */
            "lux-text": LocalJSX.LuxText & JSXBase.HTMLAttributes<HTMLLuxTextElement>;
        }
    }
}
